/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPlot, IPlotInterface } from "../IPlot";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "getPlotAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPlot__factory {
  static readonly abi = _abi;
  static createInterface(): IPlotInterface {
    return new utils.Interface(_abi) as IPlotInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IPlot {
    return new Contract(address, _abi, signerOrProvider) as IPlot;
  }
}
